### Signup
POST http://localhost:8000/api/v1/user/signUp
Content-Type: application/json

{
    "name": "jerry",
    "email": "jerry@gmail.com",
    "password" : "12345",
    "confirmPassword" : "12345"
}

###Login Route
POST http://localhost:8000/api/v1/user/signIn
Content-Type: application/json

{
    "email": "jerrydsdffyyy@gmail.com",
    "password" : "12345" 
}

###Forget passwrod
GET  http://localhost:8000/api/v1/user/forget-password
Content-Type: application/json

{
    "email": "jerry@gmail.com"
}

###Forget passwrod
PUT http://localhost:8000/api/v1/user/reset-password
Content-Type: application/json

{
    "email": "jerry@gmail.com",
    "OTP": 219873,
    "password": "1234",
    "confirmPassword" : "1234"
}







#### Refresh Token
POST http://localhost:8000/api/v1/user/refresh-token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1SUQiOiI2NTljZTkwMjM0MDI4YTIxYTM3YzU2ZGQiLCJpYXQiOjE3MDQ4OTgzMzEsImV4cCI6MTc2ODAxMzUzMSwiaXNzIjoiTGFsaXQgS3VtYXIgKEpFUlJZKSJ9.NdGMsZdTVgenenp88YO4_L0w1geuGHtM9eZgCGbM8YE"
}


##### test
POST http://localhost:8000/api/v1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1SUQiOiI2NTljZTkwMjM0MDI4YTIxYTM3YzU2ZGQiLCJpYXQiOjE3MDQ4OTg2NTUsImV4cCI6MTcwNDkwNTg1NX0.7Q1xnJEZ6UZXiRK6MakdDF0aHPaxIhRaE72NR_jMvpE